/*
 * Copyright (c) 2016, Mattto
 * All rights reserved.
 * 
 * Any usage of the source code, program or any parts
 * of it must be consulted and the permission granted 
 * by authors Ing. Matej Cenky and Ing. Jozef Bendik.
 */
package mt_main;

import java.awt.Desktop;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import static mt_main.startPanel.languageOption;

/**
 *
 * @author Jozef
 */
public class Help_Math_JDialog extends javax.swing.JDialog {

    /**
     * Creates new form Help_Math_JDialog
     */
    public Help_Math_JDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null); //center of window position
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Help_math_Jdial_1 = new javax.swing.JButton();
        Help_math_Jdial_2 = new javax.swing.JButton();
        Help_math_Jdial_3 = new javax.swing.JButton();
        Help_math_Jdial_4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        Help_math_Jdial_1.setText(language.language_label(languageOption,15));
        Help_math_Jdial_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Help_math_Jdial_1ActionPerformed(evt);
            }
        });

        Help_math_Jdial_2.setText(language.language_label(languageOption,16));
        Help_math_Jdial_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Help_math_Jdial_2ActionPerformed(evt);
            }
        });

        Help_math_Jdial_3.setText(language.language_label(languageOption,17));
        Help_math_Jdial_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Help_math_Jdial_3ActionPerformed(evt);
            }
        });

        Help_math_Jdial_4.setText(language.language_label(languageOption,18));
        Help_math_Jdial_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Help_math_Jdial_4ActionPerformed(evt);
            }
        });

        jLabel1.setText(language.language_label(languageOption,14));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Help_math_Jdial_4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Help_math_Jdial_3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Help_math_Jdial_2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Help_math_Jdial_1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Help_math_Jdial_1)
                .addGap(18, 18, 18)
                .addComponent(Help_math_Jdial_2)
                .addGap(18, 18, 18)
                .addComponent(Help_math_Jdial_3)
                .addGap(18, 18, 18)
                .addComponent(Help_math_Jdial_4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Help_math_Jdial_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Help_math_Jdial_1ActionPerformed
        if (Desktop.isDesktopSupported()) {
    try {
        String userhome = System.getProperty("user.dir");   // find home directory
        File myFile = new File(userhome + "\\resources\\Teory1MT3.pdf"); //access if and open
        Desktop.getDesktop().open(myFile);
    } catch (IOException ex) {
        // no application registered for PDFs
    } }
    }//GEN-LAST:event_Help_math_Jdial_1ActionPerformed

    private void Help_math_Jdial_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Help_math_Jdial_2ActionPerformed
       if (Desktop.isDesktopSupported()) {
    try {
        String userhome = System.getProperty("user.dir");   // find home directory
        File myFile = new File(userhome + "\\resources\\Teory2MT3.pdf"); //access if and open
        Desktop.getDesktop().open(myFile);
    } catch (IOException ex) {
        // no application registered for PDFs
    } }
    }//GEN-LAST:event_Help_math_Jdial_2ActionPerformed

    private void Help_math_Jdial_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Help_math_Jdial_3ActionPerformed
        if (Desktop.isDesktopSupported()) {
    try {
        String userhome = System.getProperty("user.dir");   // find home directory
        File myFile = new File(userhome + "\\resources\\Teory4MT3.pdf"); //access if and open
        Desktop.getDesktop().open(myFile);
    } catch (IOException ex) {
        // no application registered for PDFs
    } }
    }//GEN-LAST:event_Help_math_Jdial_3ActionPerformed

    private void Help_math_Jdial_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Help_math_Jdial_4ActionPerformed
        if (Desktop.isDesktopSupported()) {
    try {
        String userhome = System.getProperty("user.dir");   // find home directory
        File myFile = new File(userhome + "\\resources\\Teory4MT3.pdf"); //access if and open
        Desktop.getDesktop().open(myFile);
    } catch (IOException ex) {
        // no application registered for PDFs
    } }
    }//GEN-LAST:event_Help_math_Jdial_4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Help_Math_JDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Help_Math_JDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Help_Math_JDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Help_Math_JDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Help_Math_JDialog dialog = new Help_Math_JDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/mt_graphic/" + "icon.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Help_math_Jdial_1;
    private javax.swing.JButton Help_math_Jdial_2;
    private javax.swing.JButton Help_math_Jdial_3;
    private javax.swing.JButton Help_math_Jdial_4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
